### ISSUE TITLE
'Fingerprint not setted...' error appears on each page load and data stored in session is not retained.

### ISSUE THREAD

**Issue by toutavous** [crazy-max/CwsSession#1]
I truly love your session class written in combination with the tree other classes. However, I am having some challenges. First, I receive an error sign saying 'Fingerprint not setted...'. each time the page is refreshed/opened.

I also noticed that the database creates a new record (row) each time the page is refreshed and it does not retain the data stored in the session from one page to another or when the page is refreshed.

Strangely, I tried opening the same page in firefox and it only displays that error on the first load. Afterwards, the 'Fingerprint not setted...' does not appear and all data stored in session is retained between pages.

I will be very grateful if I can get help with this. I have other session classes that work well but I would prefer to use this.
![screenshot 8](https://cloud.githubusercontent.com/assets/1750049/4162205/25e4966c-34d8-11e4-99be-f4643add96e7.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/1750049/4162264/a44b1b3e-34d8-11e4-99f0-c1a8152e3e44.png)

**Comment by crazy-max** [comment]
Solved on v1.6

**Comment by crazy-max** [comment]
The first time the page is loaded, the fingerprint is not setted.
CwsSession will create a new fingerprint and regenerate the session id.

The next time the page will be loaded, the fingerprint will be used :

![fingerprint](https://cloud.githubusercontent.com/assets/1951866/8271749/80f81b68-1827-11e5-9293-50591831a0c4.png)

For you problem on duplicated rows in the databse, check that your cookie domain reflect your domain correctly.
